### GENERAL SETTINGS ###

# Site settings
title: TECLIVRE
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: UA-92767687-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://teclivre.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url: http://facabook.com/Teclivrebr
  - title: twitter
    url: http://twitter.com/roberiofig
  - title: instagram
    url: http://instagram.com/roberiofig
 
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
email: contato@portalsjcampos.com
tel: +55 (12)99775-2283


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Roberio Figueiredo
    position: CEO
    text: Estudante de engenharia, apaixonado por tecnologia.
    img: roberio.jpg
    social:
      - title: envelope #use for email address
        url: mailto:roberio@portalsjcampos.com
      - title: twitter
        url: http://twitter.com/roberiofig
  
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Teclivre, Canal voltado a quem gosta de novidade no mundo da tecnologia e software livre."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Roberio Figueiredo
    position: Desenvolvedor
